// This file is auto-generated by scripts/generate-recipes-index.mjs.
// Do not edit by hand. Run `pnpm generate:recipes` to regenerate.
import type { RecipeModuleLoader } from "./types";

export const reactRecipeLoaders: Record<string, RecipeModuleLoader> = {
	album: () => import("../../app/(app)/recipes/screens/album/album"),
	"bitcoin-price": () =>
		import("../../app/(app)/recipes/screens/bitcoin-price/bitcoin-price"),
	"bitmap-patterns": () =>
		import("../../app/(app)/recipes/screens/bitmap-patterns/bitmap-patterns"),
	calendar: () => import("../../app/(app)/recipes/screens/calendar/calendar"),
	"hacker-news": () =>
		import("../../app/(app)/recipes/screens/hacker-news/hacker-news"),
	"internet-availability": () =>
		import(
			"../../app/(app)/recipes/screens/internet-availability/internet-availability"
		),
	"local-news": () =>
		import("../../app/(app)/recipes/screens/local-news/local-news"),
	"month-of-year": () =>
		import("../../app/(app)/recipes/screens/month-of-year/month-of-year"),
	"not-found": () =>
		import("../../app/(app)/recipes/screens/not-found/not-found"),
	"responsive-example": () =>
		import(
			"../../app/(app)/recipes/screens/responsive-example/responsive-example"
		),
	"rss-feed": () => import("../../app/(app)/recipes/screens/rss-feed/rss-feed"),
	"simple-text": () =>
		import("../../app/(app)/recipes/screens/simple-text/simple-text"),
	weather: () => import("../../app/(app)/recipes/screens/weather/weather"),
	wikipedia: () =>
		import("../../app/(app)/recipes/screens/wikipedia/wikipedia"),
};

export const reactRecipeSlugs = [
	"album",
	"bitcoin-price",
	"bitmap-patterns",
	"calendar",
	"hacker-news",
	"internet-availability",
	"local-news",
	"month-of-year",
	"not-found",
	"responsive-example",
	"rss-feed",
	"simple-text",
	"weather",
	"wikipedia",
] as const;

export type ReactRecipeSlug = (typeof reactRecipeSlugs)[number];
